package ru.kode.epub.core.uikit.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColors(
  val isLight: Boolean,
  val surfaceBackground: Color,
  val surfaceLayer1: Color,
  val surfaceLayer2: Color,
  val surfaceLayer3: Color,
  val surfaceLayerContrast: Color,
  val surfaceLayerTranslucent: Color,
  val surfaceLayerAccent: Color,
  val surfaceLayerAccentPale: Color,
  val surfaceLayerPositive: Color,
  val surfaceLayerPositivePale: Color,
  val surfaceLayerNegative: Color,
  val surfaceLayerNegativePale: Color,
  val surfaceLayerWarning: Color,
  val surfaceLayerWarningPale: Color,
  val surfaceLayerOverlay: Color,
  val borderRegular: Color,
  val borderAccent: Color,
  val borderNegative: Color,
  val textPrimary: Color,
  val textSecondary: Color,
  val textTertiary: Color,
  val textQuaternary: Color,
  val textContrastPrimary: Color,
  val textContrastSecondary: Color,
  val textAccent: Color,
  val textPositive: Color,
  val textNegative: Color,
  val textWarning: Color,
  val textOnAccent: Color,
  val textOnPositive: Color,
  val textOnNegative: Color,
  val textOnWarning: Color,
  val iconPrimary: Color,
  val iconSecondary: Color,
  val iconTertiary: Color,
  val iconQuaternary: Color,
  val iconContrastPrimary: Color,
  val iconContrastSecondary: Color,
  val iconAccent: Color,
  val iconPositive: Color,
  val iconNegative: Color,
  val iconWarning: Color,
  val iconOnAccent: Color,
  val iconOnPositive: Color,
  val iconOnNegative: Color,
  val iconOnWarning: Color,
  val interactiveLayerPressed: Color,
  val interactiveLayerTranslucentDisabled: Color,
  val interactiveLayerAccentDisabled: Color,
  val interactiveLayerNegativeDisabled: Color,
  val textDisabled: Color,
  val textAccentDisabled: Color,
  val textNegativeDisabled: Color,
  val textOnAccentDisabled: Color,
  val textOnNegativeDisabled: Color,
  val iconDisabled: Color,
  val iconAccentDisabled: Color,
  val iconNegativeDisabled: Color,
  val iconOnAccentDisabled: Color,
  val iconOnNegativeDisabled: Color
)
