package ru.kode.epub.core.uikit.theme

import kotlin.collections.copy

internal val LightAppColors = AppColors(
  isLight = true,
  surfaceBackground = ColorPalette.Blue100,
  surfaceLayer1 = ColorPalette.BaseWhite,
  surfaceLayer2 = ColorPalette.Blue100,
  surfaceLayer3 = ColorPalette.BaseWhite,
  surfaceLayerContrast = ColorPalette.Neutral900,
  surfaceLayerTranslucent = ColorPalette.Blue800.copy(alpha = 0.06f),
  surfaceLayerAccent = ColorPalette.Blue600,
  surfaceLayerAccentPale = ColorPalette.Blue500.copy(alpha = 0.3f),
  surfaceLayerPositive = ColorPalette.Green600,
  surfaceLayerPositivePale = ColorPalette.Green500.copy(alpha = 0.3f),
  surfaceLayerNegative = ColorPalette.Red400,
  surfaceLayerNegativePale = ColorPalette.Red300.copy(alpha = 0.3f),
  surfaceLayerWarning = ColorPalette.Yellow500,
  surfaceLayerWarningPale = ColorPalette.Yellow400.copy(alpha = 0.3f),
  surfaceLayerOverlay = ColorPalette.BaseBlack.copy(alpha = 0.5f),
  borderRegular = ColorPalette.Blue950.copy(alpha = 0.1f),
  borderAccent = ColorPalette.Blue600,
  borderNegative = ColorPalette.Red400,
  textPrimary = ColorPalette.BaseBlack,
  textSecondary = ColorPalette.BaseBlack.copy(alpha = 0.7f),
  textTertiary = ColorPalette.BaseBlack.copy(alpha = 0.5f),
  textQuaternary = ColorPalette.BaseBlack.copy(alpha = 0.3f),
  textContrastPrimary = ColorPalette.BaseWhite,
  textContrastSecondary = ColorPalette.BaseWhite.copy(alpha = 0.8f),
  textAccent = ColorPalette.Blue700,
  textPositive = ColorPalette.Green800,
  textNegative = ColorPalette.Red500,
  textWarning = ColorPalette.Yellow800,
  textOnAccent = ColorPalette.Blue300,
  textOnPositive = ColorPalette.Green50,
  textOnNegative = ColorPalette.Red50,
  textOnWarning = ColorPalette.Yellow50,
  iconPrimary = ColorPalette.BaseBlack,
  iconSecondary = ColorPalette.BaseBlack.copy(alpha = 0.7f),
  iconTertiary = ColorPalette.BaseBlack.copy(alpha = 0.5f),
  iconQuaternary = ColorPalette.BaseBlack.copy(alpha = 0.3f),
  iconContrastPrimary = ColorPalette.BaseWhite,
  iconContrastSecondary = ColorPalette.BaseWhite.copy(alpha = 0.8f),
  iconAccent = ColorPalette.Blue700,
  iconPositive = ColorPalette.Green800,
  iconNegative = ColorPalette.Red500,
  iconWarning = ColorPalette.Yellow800,
  iconOnAccent = ColorPalette.Blue300,
  iconOnPositive = ColorPalette.Green50,
  iconOnNegative = ColorPalette.Red50,
  iconOnWarning = ColorPalette.Yellow50,
  interactiveLayerPressed = ColorPalette.Blue800.copy(alpha = 0.03f),
  interactiveLayerTranslucentDisabled = ColorPalette.Blue800.copy(alpha = 0.03f),
  interactiveLayerAccentDisabled = ColorPalette.Blue600.copy(alpha = 0.4f),
  interactiveLayerNegativeDisabled = ColorPalette.Red400.copy(alpha = 0.4f),
  textDisabled = ColorPalette.BaseBlack.copy(alpha = 0.3f),
  textAccentDisabled = ColorPalette.Blue700.copy(alpha = 0.6f),
  textNegativeDisabled = ColorPalette.Red500.copy(alpha = 0.6f),
  textOnAccentDisabled = ColorPalette.Blue300.copy(alpha = 0.6f),
  textOnNegativeDisabled = ColorPalette.Red50.copy(alpha = 0.6f),
  iconDisabled = ColorPalette.BaseBlack.copy(alpha = 0.3f),
  iconAccentDisabled = ColorPalette.Blue700.copy(alpha = 0.6f),
  iconNegativeDisabled = ColorPalette.Red500.copy(alpha = 0.6f),
  iconOnAccentDisabled = ColorPalette.Blue300.copy(alpha = 0.6f),
  iconOnNegativeDisabled = ColorPalette.Red50.copy(alpha = 0.6f),
  gradientSkeleton = listOf(ColorPalette.Neutral250, ColorPalette.Neutral100),
  gradientLinearSmall = listOf(
    ColorPalette.Neutral900.copy(alpha = 0f),
    ColorPalette.Neutral900.copy(alpha = 0.52f),
    ColorPalette.Neutral900.copy(alpha = 0.7f)
  )
)

internal val DarkAppColors = AppColors(
  isLight = false,
  surfaceBackground = ColorPalette.Blue950,
  surfaceLayer1 = ColorPalette.Neutral900,
  surfaceLayer2 = ColorPalette.Neutral800,
  surfaceLayer3 = ColorPalette.Neutral700,
  surfaceLayerContrast = ColorPalette.Neutral100,
  surfaceLayerTranslucent = ColorPalette.Blue200.copy(alpha = 0.13f),
  surfaceLayerAccent = ColorPalette.Blue400,
  surfaceLayerAccentPale = ColorPalette.Blue500.copy(alpha = 0.3f),
  surfaceLayerPositive = ColorPalette.Green400,
  surfaceLayerPositivePale = ColorPalette.Green500.copy(alpha = 0.3f),
  surfaceLayerNegative = ColorPalette.Red200,
  surfaceLayerNegativePale = ColorPalette.Red300.copy(alpha = 0.3f),
  surfaceLayerWarning = ColorPalette.Yellow300,
  surfaceLayerWarningPale = ColorPalette.Yellow400.copy(alpha = 0.3f),
  surfaceLayerOverlay = ColorPalette.BaseBlack.copy(alpha = 0.5f),
  borderRegular = ColorPalette.Blue50.copy(alpha = 0.2f),
  borderAccent = ColorPalette.Blue400,
  borderNegative = ColorPalette.Red200,
  textPrimary = ColorPalette.BaseWhite,
  textSecondary = ColorPalette.BaseWhite.copy(alpha = 0.8f),
  textTertiary = ColorPalette.BaseWhite.copy(alpha = 0.6f),
  textQuaternary = ColorPalette.BaseWhite.copy(alpha = 0.5f),
  textContrastPrimary = ColorPalette.BaseBlack,
  textContrastSecondary = ColorPalette.BaseBlack.copy(alpha = 0.7f),
  textAccent = ColorPalette.Blue400,
  textPositive = ColorPalette.Green400,
  textNegative = ColorPalette.Red200,
  textWarning = ColorPalette.Yellow300,
  textOnAccent = ColorPalette.Blue900,
  textOnPositive = ColorPalette.Green900,
  textOnNegative = ColorPalette.Red900,
  textOnWarning = ColorPalette.Yellow900,
  iconPrimary = ColorPalette.BaseWhite,
  iconSecondary = ColorPalette.BaseWhite.copy(alpha = 0.8f),
  iconTertiary = ColorPalette.BaseWhite.copy(alpha = 0.6f),
  iconQuaternary = ColorPalette.BaseWhite.copy(alpha = 0.5f),
  iconContrastPrimary = ColorPalette.BaseBlack,
  iconContrastSecondary = ColorPalette.BaseBlack.copy(alpha = 0.7f),
  iconAccent = ColorPalette.Blue400,
  iconPositive = ColorPalette.Green400,
  iconNegative = ColorPalette.Red200,
  iconWarning = ColorPalette.Yellow300,
  iconOnAccent = ColorPalette.Blue900,
  iconOnPositive = ColorPalette.Green900,
  iconOnNegative = ColorPalette.Red900,
  iconOnWarning = ColorPalette.Yellow900,
  interactiveLayerPressed = ColorPalette.Blue200.copy(alpha = 0.13f),
  interactiveLayerTranslucentDisabled = ColorPalette.Blue200.copy(alpha = 0.09f),
  interactiveLayerAccentDisabled = ColorPalette.Blue400.copy(alpha = 0.6f),
  interactiveLayerNegativeDisabled = ColorPalette.Red200.copy(alpha = 0.6f),
  textDisabled = ColorPalette.BaseWhite.copy(alpha = 0.5f),
  textAccentDisabled = ColorPalette.Blue400.copy(alpha = 0.6f),
  textNegativeDisabled = ColorPalette.Red200.copy(alpha = 0.6f),
  textOnAccentDisabled = ColorPalette.Blue900.copy(alpha = 0.6f),
  textOnNegativeDisabled = ColorPalette.Red900.copy(alpha = 0.6f),
  iconDisabled = ColorPalette.BaseWhite.copy(alpha = 0.3f),
  iconAccentDisabled = ColorPalette.Blue400.copy(alpha = 0.6f),
  iconNegativeDisabled = ColorPalette.Red200.copy(alpha = 0.6f),
  iconOnAccentDisabled = ColorPalette.Blue900.copy(alpha = 0.6f),
  iconOnNegativeDisabled = ColorPalette.Red900.copy(alpha = 0.6f),
  gradientSkeleton = listOf(ColorPalette.Neutral500, ColorPalette.Neutral550),
  gradientLinearSmall = listOf(
    ColorPalette.Neutral900.copy(alpha = 0f),
    ColorPalette.Neutral900.copy(alpha = 0.52f),
    ColorPalette.Neutral900.copy(alpha = 0.7f)
  )
)
